import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { Button, Space } from '@mantine/core';
import { AppShellDemo } from '../components/appshell'
import SendHbarForm from './sendHbarForm'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Tool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SendHbarForm></SendHbarForm>
    </div>
  )
}

export default Home
